### ISSUE TITLE
Broker fails to start if hazelcast exporter is active

### ISSUE THREAD

**Issue by pocorschi** [zeebe-io/zeebe-helm-profiles#1]
@salaboy  Hi. Been following the sample values for the helm chart. And I can't get it working with the hazelcast exporter. 

`Caused by: java.lang.IllegalStateException: Failed to load exporter with configuration: ExporterCfg{id='hazelcast', jarPath='null', className='io.zeebe.hazelcast.exporter.HazelcastExporter', args={updatePosition=false, enabledValueTypes=JOB,WORKFLOW_INSTANCE,DEPLOYMENT,INCIDENT,TIMER,VARIABLE,MESSAGE,MESSAGE_SUBSCRIPTION,MESSAGE_START_EVENT_SUBSCRIPTION}}
	at io.zeebe.broker.system.partitions.ZeebePartition.<init>(ZeebePartition.java:113)
	at io.zeebe.broker.Broker.lambda$partitionsStep$15(Broker.java:316)
	at io.zeebe.broker.bootstrap.StartProcess.lambda$startStepByStep$2(StartProcess.java:60)
	at io.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:88)
	at io.zeebe.broker.bootstrap.StartProcess.startStepByStep(StartProcess.java:58)
	at io.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:88)
	at io.zeebe.broker.bootstrap.StartProcess.start(StartProcess.java:43)
	at io.zeebe.broker.Broker.partitionsStep(Broker.java:321)`

**Comment by salaboy** [comment]
@pocorschi thanks a lot for reporting.. we did some changes into the charts that might require some of these examples alignment. 
can you help me testing those changes? 

I would recommend that in the exporters configuration try using jarPath=<location of the jar with the exporter> and keep the className as it is. That should fix the problem for now. 
In Zeebe 0.23 all these configurations are improved.. so I was waiting for that release to update the charts accordingly.

**Comment by salaboy** [comment]
I just did the changes here: https://github.com/zeebe-io/zeebe-helm-profiles/blob/master/examples/zeebe-cluster/exporters-values.yaml

**Comment by pocorschi** [comment]
Yes that seems to get it to start. I will connect to it and test it and let you know if all works as expected.

However I did have to make a change to the original charts's startupscript for zeebe-cluster

`    if [ "$(ls -A /exporters/)" ]; then
      mkdir /usr/local/zeebe/exporters/
      cp -a /exporters/*.jar /usr/local/zeebe/exporters/ 
    else  
      echo "No exporters available."
    fi`

that's because I was getting this error
`
++ ls -A /exporters/
+ '[' zeebe-hazelcast-exporter.jar ']'
+ cp -a /exporters/zeebe-hazelcast-exporter.jar /usr/local/zeebe/exporters/
cp: cannot create regular file '/usr/local/zeebe/exporters/': Not a directory
`

If that's ok I can open a PR on the main chart. Let me know

**Comment by salaboy** [comment]
@pocorschi please do open a PR.. I wonder why I didn't hit that one here.. are you running Kubernetes on prem or in a cloud provider?

**Comment by salaboy** [comment]
@pocorschi also let me know if you tweak parameters for the exporters to work.. I mean if you change parameters and you validate that those work.. we should include them in the examples.

**Comment by pocorschi** [comment]
> @pocorschi please do open a PR.. I wonder why I didn't hit that one here.. are you running Kubernetes on prem or in a cloud provider?

running on GKE. If I create the folder first with mkdir it works properly. 

I was looking to add hazelcast in order to start using https://github.com/zeebe-io/zeeqs It seems that the default hazelcast exporter port (5701) would need to be added to service.yaml and most likely the docker itself (?) So what would your suggestion be to achieve that?  Unless I'm missing something.

**Comment by salaboy** [comment]
@pocorschi I have in my TODO list to create the zeeqs Helm Charts so it all works out of the box, but for now.. yeah. you need to wire out the right ports to make it working. 
I am not sure about how zeeqs connects to hazelcast .. for what I understand the exporter needs to connect to hazelcast.. so you shouldn't open a port for that.. can you please elaborate a little bit more?

**Comment by pocorschi** [comment]
I'm not familiar with how Hazelcast works. But judging from the zeeqs docs:

> ensure that a Zeebe broker is running with a Hazelcast exporter (>= 0.8.0-alpha1)
forward the Hazelcast port to the docker container (default: 5701)
configure the connection to Hazelcast by setting io.zeebe.hazelcast.connection (default: localhost:5701)

Once you add the hazelcast exporter to the zeebe broker, it starts on a port (5701 by default) and you should point zeeqs to the zeebe svc on that port. For that an entry in service.yaml is needed. The statefulset.yaml also should expose that same port in order to have it accessible via the service. I can try to do some tests locally and do a PR if just those two changes are needed.

**Comment by pocorschi** [comment]
As far as i can see from [this thread](https://forum.zeebe.io/t/hazelcast-exporter-to-external-hazelcast-server/1062) the exporter creates an in-memory instance of hazelcast, that then can be used by zeeqs to connect to. And in order for that connection to work the two aforementioned  changes would be needed.

**Comment by salaboy** [comment]
@pocorschi yeah.. we cannot use that hazelcast from the exporter.. we should use the one from zeeqs.. let's ask @saig0

**Comment by pocorschi** [comment]
@salaboy  it's the same one according to the zeeqs docs. Im currently doing some tests with just that and will report back.

**Comment by salaboy** [comment]
great!

**Comment by saig0** [comment]
@pocorschi is correct. The Hazelcast exporter starts an in-memory Hazelcast cluster instance. ZeeQS and the other applications connect to this instance. Is this a problem? Do we need to externalize the Hazelcast cluster?

**Comment by salaboy** [comment]
@saig0 at least from the HELM charts perspective yes.. totally yes.. in-memory instances are just for development. As soon as the exporter and ZeeQS both allow us to point to which instance to connect using ENV Variables.. we should be fine.

**Comment by pocorschi** [comment]
I haven't been able to connect ZeeQS to the z-cluster launched by the helm chart. I have exposed both in the deployment.yaml (statefulset) and in the service definition the default port. I can confirm that the hazelcast exporter is running in the z-cluster but  I have a feeling that the port is not exposed properly somehow.

**Comment by salaboy** [comment]
@pocorschi that is possible.. do you know which port the hazelcast exporter should expose? maybe you can tweak the chart to get that working.. It should be another port on the statefulset definition. Probably here: https://github.com/zeebe-io/zeebe-cluster-helm/blob/master/zeebe-cluster/templates/statefulset.yaml#L69 and here in the service -> https://github.com/zeebe-io/zeebe-cluster-helm/blob/master/zeebe-cluster/templates/service.yaml#L16 to expose the port in the service itself.

**Comment by salaboy** [comment]
@pocorschi we can definitely avoid this by setting a configuration to the exporter to connect to an external hazelcast instance and the same with ZeeQS.. so that might be a better use of your time.

**Comment by salaboy** [comment]
Reference -> https://github.com/helm/charts/tree/master/stable/hazelcast

**Comment by pocorschi** [comment]
@salaboy  - Precisely where I made the modifications. And according to ZeeQS docs the default port of the hazelcast exporter is 5701. 

As for the configuration to setup the exporter to actually connect to an external Hazelcast it might be above my paygrade but definitely going to give it a try. Since neither Java nor C# are amongst my preferred languages it will make things more difficult to debug but what the hell.

**Comment by saig0** [comment]
@salaboy, I released a new version of the Hazelcast exporter (0.9.0-alpha1). It allows connecting to a remote Hazelcast instance/cluster. See https://github.com/zeebe-io/zeebe-hazelcast-exporter/pull/43.

Let me know if this works for you ;)

**Comment by pocorschi** [comment]
- deployed hazelcast standalone chart
- deployed zeebe-cluster helm with new 0.9.0-alpha1 hazelcast exporter pointing to the external hazelcast
- deployed a sample workflow on zeebe
- ran zeeqs locally pointing to the external hazecast cluster
- all good so far :)

Notes:

- I had to manually delete the z-cluster pods to force them to start properly (replicated this two times) I dont know where the issue is.
- exporter doesnt seem to want to connect if hazelcast version is 4.0 (the helm chart is using 4.0) so i downgraded it to the one used in docker compose by @saig0 which is 3.16.2

@salaboy - you mentioned working on a ZeeQS helm chart. Is there an ETA on that or should I go ahead and try my hand at one?

<img width="1343" alt="Screenshot 2020-04-25 at 12 32 03" src="https://user-images.githubusercontent.com/233198/80276330-c692bd80-86f0-11ea-94d0-829dfbd5177e.png">

**Comment by salaboy** [comment]
@pocorschi great insights.. @saig0 can we work with hazelcast 4.0? 

@pocorschi if you can copy one of the existing charts to create the zeeqs chart ... I can add that to the pipeline and release them .. so I would copy the Operate chart structure for example https://github.com/zeebe-io/zeebe-operate-helm

Create a repo with a copy of `zeebe-operate-helm` just replace the values for the zeeqs docker images  (and the chart name) and share that repo with me so I can add to the pipelines and release scripts, so it gets published to `helm.zeebe.io`

**Comment by pocorschi** [comment]
@salaboy  - cool. will do that.

**Comment by saig0** [comment]
@salaboy, I need to upgrade the dependencies. But that should be easy to do. I created an [issue](https://github.com/zeebe-io/zeebe-hazelcast-exporter/issues/46) to work on it.

**Comment by salaboy** [comment]
awesome guys!

**Comment by pocorschi** [comment]
@salaboy  - Managed to get it up and running as a [helm chart](https://github.com/pocorschi/zeeqs-helm).
A couple of things:

-  I removed the configmap as i'm using envvars to to the configuration
-  I removed the ingress entry since I think that being unprotected by default it would be potentially dangerous. Let me know if you disagree and I can add it back.

Deployed it to our cluster alongside z-cluster (with hazelcast exporter) and a hazelcast cluster and it works like a charm. Now just waiting for @saig0  to bring the exporter up to latest.

Let me know if you need anything else.

**Comment by salaboy** [comment]
@pocorschi great! I will take a look on Monday and see if I can hook it up to helm.zeebe.io

**Comment by salaboy** [comment]
Regarding: 
"I removed the ingress entry since I think that being unprotected by default it would be potentially dangerous. Let me know if you disagree and I can add it back."
Yeah that is perfect.. no need for an ingress for an internal service .. at least not for now.

**Comment by salaboy** [comment]
I will close this issue as what we need is probably a blog post explaining how to set this up with the new chart which was published here: https://github.com/zeebe-io/zeebe-zeeqs-helm
