### ISSUE TITLE
zeebe-full with dev profile on docker for windows k8s cluster

### ISSUE THREAD

**Issue by ionutcalin** [zeebe-io/zeebe-helm-profiles#6]
Hello, I'm trying to start the full helm chart for zeebe on my dev machine with the following setup:
- OS: Windows 10 20H2 (WSL2 activated)
- Docker for Windows 20.10.0
- Kubernetes (activated in Docker For Windows): 1.19.3 
- Helm: v3.4.2

I also applied the changes on the k8s objects mentioned in helm-service-account-role (as specified in https://docs.zeebe.io/kubernetes/installing-helm.html)
   Obs.:  when running the kubectl --apply ...  I had warnings that the v1beta1 version of the api (apiVersion: rbac.authorization.k8s.io/v1beta1) does not exists so it switch back to V1 

the installation was done using the dev profile from this git repository
helm install my-zeebe zeebe/zeebe-full -- values https://raw.githubusercontent.com/zeebe-io/zeebe-helm-profiles/master/zeebe-dev-profile.yaml

And here the problems started (there are 2 of them)
1) Even if I was using the dev-profile values file it was still trying to install 3 instances of the zeebe broker and 3 elasticsearch instances.  
    This I figured out is because the names of the charts inside the zeebe-dev-profile.yaml are not corresponding to the ones in the latest version of the zeebe-full chart, so I passed over by downloading the yaml file and do the following corrections: 
    change zeebe-cluster-helm to zeebe
    change zeebe-operate-helm to operate
    change zeebe-tasklist-helm to tasklist
    change zeebe-zeeqs-helm to zeeqs

After doing the changes and run the helm install with my local values yaml file Pb 1 from above was solved so that now it was 1 instance of elastic and one instance of zeebe broker deployed, but now I have another problem
2) The zeebe borker instance is not starting

NAME                                                                                READY   STATUS    RESTARTS   AGE  
elasticsearch-master-0                                                         1/1     Running       0             2m26s
my-nginx-ingress-controller-5697f87674-pngpp                1/1     Running       0             2m26s
my-nginx-ingress-default-backend-fd5c8b6d4-l6vd8         1/1     Running       0            2m26s
my-operate-5775bdd89d-bxlvq                                           1/1     Running       0            2m26s
**my-zeebe-0                                                                           0/1     Running      0            2m26s**
my-zeebe-gateway-7d84fcb8b4-knnz7                                1/1     Running      0            2m26s

So looking in the logs of the pod I see this
2020-12-29 12:26:30.048 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [6/10]: cluster services
2020-12-29 12:26:35.342 [] [raft-server-0-raft-partition-partition-1] WARN  io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Poll request to 2 failed: java.net.ConnectException: Expected to send 
a message with subject 'raft-partition-partition-1-poll' to member '2', but member is not known. Known members are '[Member{id=my-zeebe-gateway-7d84fcb8b4-knnz7, address=10.1.0.81:26502, properties={event-service-topics-subscribed=HwEBAwFqb2JzQXZhaWxhYmzl}}, Member{id=0, address=my-zeebe-0.my-zeebe.default.svc.cluster.local:26502, properties={}}]'.
2020-12-29 12:26:35.342 [] [raft-server-0-raft-partition-partition-1] WARN  io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Poll request to 1 failed: java.net.ConnectException: Expected to send 
a message with subject 'raft-partition-partition-1-poll' to member '1', but member is not known. Known members are '[Member{id=my-zeebe-gateway-7d84fcb8b4-knnz7, address=10.1.0.81:26502, properties={event-service-topics-subscribed=HwEBAwFqb2JzQXZhaWxhYmzl}}, Member{id=0, address=my-zeebe-0.my-zeebe.default.svc.cluster.local:26502, properties={}}]'.

Somehow raft is still expecting to have 3 members in the cluster to monitor not 1 as is indicated in the dev profile value file (clusterSize: 1) and is trying to pool the followers which of course does not exists.

So, if for the first problem (wrong naming in the dev profile) I could overcome by having a local file with correct naming, the second one I'm not able to figure out from where it is even if I activated the debug level for the logging in the zeebe broker.

Regards,
ionut

**Comment by salaboy** [comment]
Hi @ionutcalin thanks for reaching out.. It might be the case that your kubernetes resources are not enough to run all the pods.. I will fix the profiles soon.. Probably nxt week when I get back from holidays. Can you check your docker and kubernetes config (check memory and CPU)

**Comment by E-Acosta** [comment]
Still no solution for this problem? I am having the exact same. When I start with the dev profile it loads me 3 instances of elasticsearch and zeebe.

**Comment by salaboy** [comment]
@E-Acosta I think this should be working already. How are you starting the dev profile?

**Comment by salaboy** [comment]
can you try with helm install my-zeebe zeebe/zeebe-full-helm -- values https://raw.githubusercontent.com/zeebe-io/zeebe-helm-profiles/master/zeebe-dev-profile.yaml

**Comment by ionutcalin** [comment]
Now it works
